name: Release on push

on:
  push:
    branches:
      - master
        
jobs: 
  Release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: '6.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Publish solution
        run: dotnet publish -c Release -o publish
      - name: Get latest tag
        run: echo "::set-output name=value::$(git describe --tags --abbrev=0)"
        id: latest-tag
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.latest-tag.outputs.value }}
          files: ${{ github.workspace }}/publish/OsuPackImporter.exe
          body_path: ${{ github.workspace }}/CHANGELOG.md
